services:
  memcached:
    environment:
      MEMCACHED_CACHE_SIZE: '128'
    image: memcached:latest
    ports:
    - published: 11211
      target: 11211
  mysql:
    environment:
      MYSQL_DATABASE: app1_db
      MYSQL_PASSWORD: cisco123
      MYSQL_ROOT_PASSWORD: Cisco@123
      MYSQL_USER: cisco
      DEBUG: 'false'
    image: mysql:latest
    ports:
    - published: 33060
      target: 3306
    restart: always
    volumes:
    - db_data:/var/lib/mysql
  postgres:
    container_name: my_postgres
    environment:
      DB_NAME: app1_db
      DB_PASS: cisco123
      DB_USER: cisco
      DEBUG: 'false'
    image: postgres:latest
    ports:
    - published: 54320
      target: 5432
    volumes:
    - db_data:/var/lib/postgresql/data
  apache2:
    build:
      context: .
    command: server
    image: apache2:latest
    ports:
    - published: 80
      target: 80
    volumes:
    - ./base_site:/var/www/base_site:rw
    - ./apache_django.conf:/etc/apache2/sites-available/000-default.conf:rw
    - ./startup.sh:/var/www/startup.sh:rw
version: '3.7'
volumes:
  db_data: {}
